# Generated by Django 6.0.6 on 2026-07-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_patient_created_at_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prescription', models.TextField()),
                ('allergies', models.CharField(default='None', max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('sugar_level', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='hospital_app.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
                'unique_together': {('patient', 'visit_date')},
            },
        ),
    ]
