# Generated by Django 5.2.7 on 2026-07-16 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_alter_appointment_id_alter_bill_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50, unique=True)),
                ('bed_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('General', 'General'), ('Semi-Private', 'Semi-Private'), ('Private', 'Private'), ('ICU', 'ICU')], max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('number_of_beds', models.IntegerField()),
                ('charges_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBedAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hospital_app.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hospital_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital_app.room'),
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('from_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='hospital_app.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hospital_app.patient')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='hospital_app.bed')),
            ],
        ),
    ]
