# Generated by Django 6.0.6 on 2026-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_alter_medicalhistory_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20),
        ),
    ]
