# Generated by Django 6.0.6 on 2026-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
